### ISSUE TITLE
Backup hangs with .pipe file

### ISSUE THREAD

**Issue by Zaharid** [linuxmint/mintbackup#16]
I was trying to backup my home dir, which contains the file .stream/stream.pipe. The backup tool stays forever displaying that file when it reaches it and never advances to the next.

I was trying to obtain a .tar.bz2 file of my backup.

**Comment by thorsummoner** [comment]
Also hangs on FOFI files :(

**Comment by SethosII** [comment]
This should be fixed by https://github.com/linuxmint/mintbackup/commit/9389fc8480075ff591d1475c5bba6dc379f3212b. Can you test it again?
