### ISSUE TITLE
Add popular cloud storages

### ISSUE THREAD

**Issue by edmundlaugasson** [linuxmint/mintbackup#17]
I would propose to add popular cloud storages - http://www.free-online-backup-services.com/
I mean that chosen cloud storage would be possible to use as backup storage.
E.g. ownCloud, SurDoc, MegaSync, hubic, Google Drive, Dropbox, Amazon Cloud Drive, Box, iCloud etc. Some of them might not have Linux client but e.g. WebDAV would be possible (e.g. Box).

**Comment by clefebvre** [comment]
This should be integrated via the file manager / OS and accessible via Gtk.FileChooser. Once mounted locally it should make no difference for the tool.
