### ISSUE TITLE
excluded paths tree view doesn't display first two characters of paths

### ISSUE THREAD

**Issue by thorsummoner** [linuxmint/mintbackup#23]
OS: Mint 17.1 upgraded to 17.3

Action: Backup Files -> From: File System, To: usb hard drive subdirectory (`/media/<user>/<diskid>/backups/<hostname>`)

Add excluded directories: `/media/`

The `/m` of `/media/` does not show in the excluded paths treeview.

![image](https://cloud.githubusercontent.com/assets/1320336/14067721/201bd8ae-f420-11e5-8422-950b03e05c35.png)

I added several other paths (to .pipe and .fifo files that the checksum hangs on) and they were all missing the first two characters of their path too.

**Comment by clefebvre** [comment]
Fixed after revamp on git master.
