### ISSUE TITLE
hardcoded icon for mintbackup

### ISSUE THREAD

**Issue by erikdubois** [linuxmint/mintbackup#28]
mintbackup.desktop in /usr/applications

has a hardcoded link to an image
Exec=mintbackup
**Icon=/usr/share/pixmaps/mintbackup/icon.svg**
Terminal=false
Type=Application
Encoding=UTF-8
Categories=Application;System;Settings
NotShowIn=KDE;

change 

**Icon=/usr/share/pixmaps/mintbackup/icon.svg**

to
**Icon=mintbackup**

**Comment by erikdubois** [comment]
this is the last icon that is hardcoded. It breaks the design when you change the icons. As I am particularly busy in making linux mint more appealing by making icons your help would be appreciated. I can understand that there are other priorities. Any idea when we can expect this change?

**Comment by erikdubois** [comment]
this problem is also in KDE
Checking KDE BETA VERSION
These three programs will always break your icon theme.
hardcoded icon in the desktop file at /usr/share/applications
Just put a name with extension like 'backup' and put a backup icon in hicolor svg or png
https://plus.google.com/+ErikDubois/posts/d3YjtXADjMc

**Comment by erikdubois** [comment]
![mint-hardcoded-icons](https://cloud.githubusercontent.com/assets/10594806/18834757/00f7fc1a-83f8-11e6-8b77-346ddb5320c7.gif)

**Comment by JosephMcc** [comment]
I'll take a look at fixing both of these.

**Comment by erikdubois** [comment]
thanks
