### ISSUE TITLE
Crash on saving software list

### ISSUE THREAD

**Issue by Xodetaetl** [linuxmint/mintbackup#33]
Trying to save the installed software list, mintbackup gets busy for a bit then crashes (when it's done getting the list, I think):

```
Gdk-ERROR **: The program 'mintbackup.py' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadAlloc (insufficient resources for operation)'.
  (Details: serial 8068 error_code 11 request_code 130 (MIT-SHM) minor_code 5)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

It looks like a threading issue.

**Comment by troyheron** [comment]
I have same problem. Using 2.2.2

**Comment by PapayaMedia** [comment]
Same issue in version 2.2.4

**Comment by Mintulix** [comment]
Same issue after upgrade to Selena, LM18.1 64bit:
It's also noticeable that there's no filename to save as it used to be, just choose the folder, press next and crash.
Last time I used this tool with success was 4th July 2016 (but I don't know the program version of course).

**Comment by clefebvre** [comment]
Threading code was completely revamped today on git master.
