### ISSUE TITLE
No way to get a version# without using package manager

### ISSUE THREAD

**Issue by dg1727** [linuxmint/mintbackup#38]
There is no version# in the GUI (or if there is, it's hidden), and command lines `mintbackup --version` and `mintbackup --help` just launch the GUI as though no command-line option had been given.  

`mintbackup` APT package 2.2.7

**Comment by clefebvre** [comment]
apt is able to give the version of any package on the system.

apt version mintbackup.

It isn't a requirement for each app to be able to show its version. Ideally we do so in an About window, but without a menubar or toolbar, we just do not provide this feature here.
