### ISSUE TITLE
[feature request] logging or option to save the log file

### ISSUE THREAD

**Issue by camypaj** [linuxmint/mintbackup#40]
Hi Mint Devs and all,

thanks for the amazing distro, and this great handy tool for backup.
Unfortunately, I've ran into some hiccups using it (combo of kernel version and controller chip on my external drive), and that is why I've noticed that I cannot find the logs from the tool anywhere, and I cannot save/select/copy the resulting error log file, containing the list of files that failed, and the reason why it failed, for example.

So, do you think it would be too much trouble to implement some kind of logging? It would also be convenient to be able to check up on progress of a longer backup job, over ssh.

Thanks & regards,
camypaj

**Comment by clefebvre** [comment]
Hi,

I would suggest using rsync over ssh, or tar directly with a pipe.

The scope of this tool is solely to be run graphically and to show errors within the window when things go bad.

**Comment by camypaj** [comment]
Hi Clem,

thanks for the clarification.

Regards
