### ISSUE TITLE
Duplicate entries in exclude list

### ISSUE THREAD

**Issue by ilsh1964** [linuxmint/mintbackup#44]
mintbackup version: 2.2.8 (latest dev version)
Always appear 2 duplicate dirs in exclude list (~/Documents/Backups)
I remove them and they appear again in the next backup...

**Comment by clefebvre** [comment]
Fixed.

**Comment by letuxmasque** [comment]
similar problem with mintbackup ver 2.3.4
each time I make a new backup in ~/Documents/Backups, a new line with same path is added in exclude list :
![screenshot from 2018-06-19 18-26-22](https://user-images.githubusercontent.com/36480615/41611997-d8636a14-73f1-11e8-8af6-d54d4f25b7dc.png)
