### ISSUE TITLE
error while restoring the software selection

### ISSUE THREAD

**Issue by Mintulix** [linuxmint/mintbackup#47]
Steps to reproduce:
1. Saved the software selection (Mint 18.2 Cinnamon 64), partly with PPA software
2. Fresh install of Mint 18.3 Cinnamon 64
3. Full update, mintbackup is v. 2.3.1
4. No PPA entries in sources yet
5. Start mintbackup and try to restore the software selection
6. Error message with any first entry in the list that belongs to the PPAs (correctly listet with "package could not be found")
7. Installation of any software in the list is not startet

The message is
Ein unvorhergesehener Fehler ist aufgetreten
Anscheinend gibt es einen Programmfehler in aptdaemon, der Anwendung, die Ihnen das Installieren/Entfernen von Anwendungen und das Ausführen weiterer Paketverwaltungsaufgaben ermöglicht.
Details:
org.debian.apt: mintinstall-icons
<small>Das Paket konnte nicht gefunden werden.< isn't a valid package name

How it should work:
Software in the list, that is not available anymore, should be ignored like in older versions of mintbackup.

**Comment by clefebvre** [comment]
I disagree. This gives you the option to add your PPA and reinstall these packages.

**Comment by Mintulix** [comment]
Hi Clem, this is right, but I don't want to install most of the PPAs again and of course none of their packages, just restore available packages. To add PPAs only to to be able to reinstall packages from the main repository is very inconvenient.
