### ISSUE TITLE
after upgrade from 18.2 to 18.3 mintbackup cannot see any of my installed programs

### ISSUE THREAD

**Issue by calexil** [linuxmint/mintbackup#49]
![screenshot at 2018-02-23 15-18-17](https://user-images.githubusercontent.com/3487071/36615034-ce291e04-18ac-11e8-9aa8-d68f4615fd54.png)

**Comment by xenopeek** [comment]
This is directly related to https://github.com/linuxmint/mintinstall/issues/172. mintinstall and mintbackup only show you programs you installed (while on Linux Mint 18.3) through mintinstall. Possible change in how mintinstall works will also affect mintbackup.
