### ISSUE TITLE
The tool's file browser lacks an option to make a new folder

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/mintbackup#50]
That option is one that one might want - I wanted it - when making a backup.

**Comment by JosephMcc** [comment]
Are you guys talking about the one here:

![backup tool_014](https://user-images.githubusercontent.com/2231759/39412133-4fc51ae2-4bcc-11e8-9d47-eadb129a1966.png)

**Comment by CottonEaster** [comment]
Well, it's been a while since I reported this problem, but I was . . complaining that the MintBackup Tool does not allow one to create a new folder; and, yes, the window that you provide an image of, Joseph, is at issue.
