### ISSUE TITLE
Mint 19 Backup tool fails to parse software selection from com.linuxmint.install installed-apps

### ISSUE THREAD

**Issue by smurphos** [linuxmint/mintbackup#55]
mintbackup version 2.3.4
mintinstall version 7.9.4
Kernel: 4.15.0-24-generic x86_64 bits: 64 
compiler: gcc v: 7.3.0 Desktop: Cinnamon 3.8.7 Distro: Linux Mint 19 Tara 
base: Ubuntu 18.04 LTS Bionic 

Issue: mintinstall is adding software to com.linuxmint.install installed-apps in the format `'apt:package-name1', 'apt:package-name2'` etc. 

`mintbackup.py` is failing to parse this list to produce a list of installed software. The list displays fine in Software Manager.

If individual entries in com.linuxmint.install installed-apps are manually edited to remove the `apt:` prefix those packages are then listed in both the Backup Tool and Software Manager.

Behaviour compared in an up to date 18.3 install. There `com.linuxmint.install installed-apps` is in format `'package-name1','package-name2'` by default and both applications parse the list successfully.

![screenshot-screen-2018-07-06-045025](https://user-images.githubusercontent.com/29017677/42359148-35e809a4-80d8-11e8-8f9b-375542a8b45a.png)
![screenshot-screen-2018-07-06-044917](https://user-images.githubusercontent.com/29017677/42359149-3601ab20-80d8-11e8-9b08-78dd57aefc5a.png)

**Comment by clefebvre** [comment]
Fixed by @nextgensparx in 2.3.5.
