### ISSUE TITLE
Bad bug in French translation

### ISSUE THREAD

**Issue by gm10** [linuxmint/mintbackup#58]
French translation being the opposite of the (correct) English version:
```
#: usr/share/linuxmint/mintbackup/mintbackup.ui.h:12
msgid ""
"Hidden files and hidden folders located at the root of your home directory "
"are not included by default."
msgstr ""
"Les fichiers et dossiers cachés situés à la racine de votre dossier "
"personnel sont inclus par défaut."
```

French text should be:
```
"Les fichiers et dossiers cachés situés à la racine de votre dossier "
"personnel sont exclus par défaut."
```

PS: I would have reported this for the mint-translations package where this belongs but issues cannot be submitted for that one

**Comment by xenopeek** [comment]
The current French translation for this [string](https://translations.launchpad.net/linuxmint/latest/+pots/mintbackup/fr/39/+translate) is: "Les fichiers et dossiers cachés situés à la racine de votre dossier personnel **ne** sont pas inclus par défaut". That looks correct. 

Translation is done on Launchpad. New/improved translations are periodically pulled from Launchpad into the GitHub projects. See also our[ translation guide](https://linuxmint-translation-guide.readthedocs.io/en/latest/).

**Comment by gm10** [comment]
@xenopeek fair enough, I hadn't looked into how translations are done, just reported this after some guy on the forums was wondering why he lost all of his settings after using mintbackup and re-installing. That's what makes this a critical bug, so the fixed translation should be pushed soon and backported as well, just saying it's fixed on launchpad doesn't give it the priority it deserves. 

Also goes for the open pull request for this package by the way, that part of mintbackup's functionality has been broken on LM19 since release. Things like this is why I keep saying that Mint is barely supported despite what clem says.
