### ISSUE TITLE
Restoring from manual backup

### ISSUE THREAD

**Issue by AndreiMiculita** [linuxmint/mintbackup#80]
How would I restore from a manual backup (i.e. just a home dir that's been copied to another device?) 

ecryptfs got (quite spontaneously) borked on my device, and long story short, I managed to copy the (unencrypted) home directory to an external hard drive.

I've given up on trying to fix my current install of Mint, and will just reinstall and restore everything.

But the backup I have is
1) not a .tar but just an actual directory
2) missing .meta.mint

These are the differences I've spotted so far. 

As far as I can tell, running `sudo tar -c -f -v backup.tar backeduphomedir/`
followed by
`tar -tf backup.tar | wc -l`
 and just creating a .meta.mint text file (with `num_files: [the number from the previous command]`), should recreate the backup creation process exactly. Is this right?

**Comment by xenopeek** [comment]
If you already have copied your files to external hard disk, why don't you simply copy them back from there to your home directory after reinstalling Linux Mint? You don't need mintbackup for that.

**Comment by AndreiMiculita** [comment]
Well, that's what I'll probably do. Was just worried that replacing the entire /home/ dir while logged in would break things.

**Comment by mexsudo** [comment]
I suggest just copy your Personal files, not everything (not the 
settings/hidden files).

do you have Two usb ports?
if so boot with a Live OS (installer USB would work) to do your file 
management After the fresh install.

**Comment by AndreiMiculita** [comment]
@mexsudo I do have two USB ports, thanks for the tip. I want to keep a bunch of hidden files (.bashrc, Firefox profiles, themes, Cinnamon config etc) so I'd prefer to copy those too. I assume it should be relatively safe if I do it from the live USB (and use the same version for all software)? The tradeoff in risk/time saved seems worth it to me

**Comment by mexsudo** [comment]
On 2/2/22 06:49, Andrei Miculita wrote:
>
> @mexsudo <https://github.com/mexsudo> I do have two USB ports, thanks 
> for the tip. I want to keep a bunch of hidden files (.bashrc, Firefox 
> profiles, themes, Cinnamon config etc) so I'd prefer to copy those 
> too. I assume it should be relatively safe if I do it from the live 
> USB (and use the same version for all software)?
>
you will "probably" be OK.

I typically copy the .mozilla folder, and my conky files in the .config 
folder.

If it breaks, start over and be more selective.

best if luck!
